# La salida del templo

Entraron en la nueva sala y las puertas de piedra se cerraron tras ellos. Se giraron sobre sí mismos y observaron la gran y solitaria habitación en la que se encontraban.

Volvían a estar entre 4 paredes de piedra tan altas como las anteriores. Esta vez solo 2 de ellas tenían una ventana pequeña y cuadrada en lo más alto. La pared que quedaba tras ellos tenía solamente la gran puerta por la que habían entrado. Y en la pared opuesta podía verse otra puerta muy diferente a todas las anteriores.

Esta nueva puerta era un poco más pequeña y brillaba, pues era de oro macizo. Pero lo que más emocionó a Pyratilla y su tripulación fue que en letras grandes y brillantes ponía: SALIDA AL EXTERIOR. A punto estaban de correr hacia la puerta cuando en el centro de la habitación apareció un altar. Con cautela, los tres piratas se acercaron al altar.

El primero en llegar fue Pyratilla y en voz alta empezó a leer:

<dl>
<dd>"Esta es la prueba final:</dd>
<dd>al superarla al exterior podrás salir</dd>
<dd>un cuadrado perfecto vas a crear</dd>
<dd>y para ello las instrucciones debes seguir."</dd>
</dl>

Al pronunciar la última palabra, el texto del altar cambió mágicamente y ahora se leía:

<dl>
<dd>"INSTRUCCIONES:</dd>
<dd>Utiliza el módulo numpy</dd>
<dd>Dados los arrays a, b, c, d y e, concátenalos de modo que</dd>
<dd>* sea un array bidimensional</dd>
<dd>* su shape sea (5, 5)</dd>
<dd>* cada fila sume 65</dd>
<dd>* cada columna sume 65</dd>
<dd>* cada diagonal sume 65</dd>
<dd>PISTA: El número de la mala suerte ocupa el lugar central</dd>
<dd>Cuando lo hayas construido,</dd>
<dd>* comprueba la dimensión con el método correspondiente</dd>
<dd>* comprueba la shape con el método correspondiente</dd>
<dd>* comprueba que cada fila suma 65 con el método correspondiente</dd>
<dd>* comprueba que cada columna suma 65 con el método correspondiente</dd>
<dd>* comprueba que cada diagonal suma 65 con un método creado por ti</dd>
<dd>* con el método .ndenumerate() indica los índices de los elementos que son mayores a la media de los elementos del array bidimensional construido y los que no lo son</dd>
<dd>* muestra los elementos que sí han superado el filtro de ser mayores a la media de los elementos del array bidimensional construido"</dd>

</dl>


In [1]:
import numpy as np

In [2]:
a = np.array([[17, 5, 13, 21, 9]])
b = np.array([[23, 6, 19, 2, 15]])
c = np.array([[4, 12, 25, 8, 16]])
d = np.array([[11, 24, 7, 20, 3]])
e = np.array([[10, 18, 1, 14, 22]])

In [21]:
def diagonal_sum(array):
    sum_pdiag = 0
    sum_sdiag = 0
    for i in range(len(array)):
        for j in np.nditer(concat_array[i, i::5]):
            sum_pdiag += j
        for k in np.nditer(concat_array[i, (len(concat_array)-1)-i::5]):
            sum_sdiag += k
    return (sum_pdiag, sum_sdiag)

concat_array = np.concatenate((d,c,a,e,b), axis = 0)
print(concat_array)
print("Dimensión = {}".format(concat_array.ndim))
print("Shape = {}".format(concat_array.shape))
print("La suma de las filas es: {}".format(np.sum(concat_array, axis=0)))
print("La suma de las columnas es: {}".format(np.sum(concat_array, axis=1)))
print("La suma de la diagonal principal es: {}".format(diagonal_sum(concat_array)[0]))
print("La suma de la diagonal secundaria es: {}".format(diagonal_sum(concat_array)[1]))

[[11 24  7 20  3]
 [ 4 12 25  8 16]
 [17  5 13 21  9]
 [10 18  1 14 22]
 [23  6 19  2 15]]
Dimensión = 2
Shape = (5, 5)
La suma de las filas es: [65 65 65 65 65]
La suma de las columnas es: [65 65 65 65 65]
La suma de la diagonal principal es: 65
La suma de la diagonal secundaria es: 65


In [39]:
mean = np.sum(concat_array) / (concat_array.shape[0] * concat_array.shape[1])

for idx, i in np.ndenumerate(concat_array):
    print("El número {} de indice {} es {} a la media".format(i, idx, "mayor o igual" if i >= mean else "menor"))

El número 11 de indice (0, 0) es menor a la media
El número 24 de indice (0, 1) es mayor o igual a la media
El número 7 de indice (0, 2) es menor a la media
El número 20 de indice (0, 3) es mayor o igual a la media
El número 3 de indice (0, 4) es menor a la media
El número 4 de indice (1, 0) es menor a la media
El número 12 de indice (1, 1) es menor a la media
El número 25 de indice (1, 2) es mayor o igual a la media
El número 8 de indice (1, 3) es menor a la media
El número 16 de indice (1, 4) es mayor o igual a la media
El número 17 de indice (2, 0) es mayor o igual a la media
El número 5 de indice (2, 1) es menor a la media
El número 13 de indice (2, 2) es mayor o igual a la media
El número 21 de indice (2, 3) es mayor o igual a la media
El número 9 de indice (2, 4) es menor a la media
El número 10 de indice (3, 0) es menor a la media
El número 18 de indice (3, 1) es mayor o igual a la media
El número 1 de indice (3, 2) es menor a la media
El número 14 de indice (3, 3) es mayor o ig

In [42]:
concat_array_filter = concat_array[concat_array > mean]
print("Los elementos que han superado el filtro de ser mayor a la media son: {}".format(concat_array_filter))

Los elementos que han superado el filtro de ser mayor a la media son: [24 20 25 16 17 21 18 14 22 23 19 15]
